{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "password-vault.fullname" . }}-api
  namespace: {{ include "password-vault.namespace" . }}
  labels:
    {{- include "password-vault.labels" . | nindent 4 }}
spec:
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  selector:
    matchLabels:
      {{- include "password-vault.selectorLabels" . | nindent 6 }}
{{- end }}
