apiVersion: v1
kind: Service
metadata:
  name: {{ include "password-vault.fullname" . }}-api
  namespace: {{ include "password-vault.namespace" . }}
  labels:
    {{- include "password-vault.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "password-vault.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
